apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "https://github.com/juancarlos-cloud/addons-argocd.git"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kube-system
