resources:
  - ../../../base/alb-controller/

patches:
  - target:
      kind: Application
    patch: |-
      - op: add
        path: /spec/source/helm/valueFiles/1
        value: $values/clusters/eks-test/alb-controller/values.yaml
